### ISSUE TITLE
Assembler errors when building openssl.

### ISSUE THREAD

**Issue by amal-khailtash** [cloudmatrix/myppy#7]
I tried this on a RHEL 5.5 and Ubuntu 12.04 beta.  The idea of a portable python on Linux is great, hopefully you can make it work.

When I try to create a new environment on Ubuntu, I get the following errors:

x86cpuid.s: Assembler messages:
x86cpuid.s:8: Error: invalid instruction suffix for `push'
x86cpuid.s:9: Error: invalid instruction suffix for`push'
x86cpuid.s:10: Error: invalid instruction suffix for `push'
x86cpuid.s:11: Error: invalid instruction suffix for`push'
x86cpuid.s:13: Error: invalid instruction suffix for `pushf'
x86cpuid.s:14: Error: invalid instruction suffix for`pop'
x86cpuid.s:17: Error: invalid instruction suffix for `push'
x86cpuid.s:18: Error: invalid instruction suffix for`popf'
x86cpuid.s:19: Error: invalid instruction suffix for `pushf'
x86cpuid.s:20: Error: invalid instruction suffix for`pop'
x86cpuid.s:99: Error: invalid instruction suffix for `pop'
x86cpuid.s:100: Error: invalid instruction suffix for`pop'
x86cpuid.s:101: Error: invalid instruction suffix for `pop'
x86cpuid.s:102: Error: invalid instruction suffix for`pop'
x86cpuid.s:114: Error: invalid instruction suffix for `pop'
x86cpuid.s:116: Error: relocated field and relocation type differ in signedness
x86cpuid.s:130: Error: invalid instruction suffix for`pop'
x86cpuid.s:132: Error: relocated field and relocation type differ in signedness
x86cpuid.s:138: Error: invalid instruction suffix for `pushf'
x86cpuid.s:139: Error: invalid instruction suffix for`pop'
x86cpuid.s:143: Error: invalid instruction suffix for `push'
x86cpuid.s:144: Error: invalid instruction suffix for`push'
x86cpuid.s:161: Error: invalid instruction suffix for `pushf'
x86cpuid.s:162: Error: invalid instruction suffix for`pop'
x86cpuid.s:192: Error: invalid instruction suffix for `pop'
x86cpuid.s:194: Error: relocated field and relocation type differ in signedness
x86cpuid.s:221: Error: invalid instruction suffix for`push'
x86cpuid.s:230: Error: invalid instruction suffix for `pop'
x86cpuid.s:238: Error: invalid instruction suffix for`push'
x86cpuid.s:257: Error: invalid instruction suffix for `pop'
make[1]: *** [x86cpuid.o] Error 1
make[1]: Leaving directory`/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d/crypto'
make: **\* [build_crypto] Error 1
make: Leaving directory `/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d'
Traceback (most recent call last):
  File "./build/scripts-2.7/myppy", line 6, in <module>
    res = myppy.main(sys.argv)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/**init**.py", line 164, in main
    res = cmd.run(target,args) or 0
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/**init**.py", line 179, in run
    target.init()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 113, in init
    self.install(dep,initialising=True,explicit=False)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 198, in install
    self.install(dep,initialising=initialising,explicit=False)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 206, in install
    r.build()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/recipes/base.py", line 86, in build
    self._make()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/recipes/base.py", line 105, in _make
    self._generic_make()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/recipes/linux.py", line 81, in _generic_make
    self.target.do(_cmd,env=env)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 139, in do
    subprocess.check_call(cmdline,env=env,stdin=stdin,_*kwds)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', 'CC=apgcc', 'CXX=apg++', '-C', u'/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d/.')' returned non-zero exit status 2

I searched the net and I made the following change to the openssl recipe:
# CONFIGURE_ARGS = ["linux-elf","shared"]

```
CONFIGURE_ARGS = ["linux-x86_64","shared"]
```

the assembler errors went away, but I get the following errors:

```
    APPNAME=openssl OBJECTS="openssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o" \
    LIBDEPS=" $LIBRARIES -ldl" \
    link_app.${shlib_target}
```

make[2]: Entering directory `/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d/apps'
ca.o: In function`ca_main':
ca.c:(.text+0x1a26): undefined reference to `__ctype_toupper@GLIBC_2.0'
enc.o: In function`show_ciphers':
enc.c:(.text+0xb): undefined reference to `__ctype_b@GLIBC_2.0'
s_server.o: In function`s_server_main':
s_server.c:(.text+0x2a53): undefined reference to `__ctype_b@GLIBC_2.0'
s_client.o: In function`s_client_main':
s_client.c:(.text+0x1012): undefined reference to `__ctype_b@GLIBC_2.0'
rand.o: In function`rand_main':
rand.c:(.text+0x1c0): undefined reference to `__ctype_b@GLIBC_2.0'
../libcrypto.so: undefined reference to`**ctype_tolower'
../libcrypto.so: undefined reference to `__ctype_b'
collect2: ld returned 1 exit status
make[2]: *** [link_app.gnu] Error 1
make[2]: Leaving directory`/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d/apps'
make[1]: **\* [openssl] Error 2
make[1]: Leaving directory `/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d/apps'
make: *** [build_apps] Error 1
make: Leaving directory`/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d'
Traceback (most recent call last):
  File "./build/scripts-2.7/myppy", line 6, in <module>
    res = myppy.main(sys.argv)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/__init**.py", line 164, in main
    res = cmd.run(target,args) or 0
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/**init**.py", line 179, in run
    target.init()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 113, in init
    self.install(dep,initialising=True,explicit=False)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 198, in install
    self.install(dep,initialising=initialising,explicit=False)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 206, in install
    r.build()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/recipes/base.py", line 86, in build
    self._make()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/recipes/base.py", line 105, in _make
    self._generic_make()
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/recipes/linux.py", line 81, in _generic_make
    self.target.do(_cmd,env=env)
  File "/home/amal/work/myppy/build/lib.linux-x86_64-2.7/myppy/envs/base.py", line 139, in do
    subprocess.check_call(cmdline,env=env,stdin=stdin,_*kwds)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', 'CC=apgcc', 'CXX=apg++', '-C', u'/home/amal/work/ppy/build/openssl-1.0.0d.tar.gz/openssl-1.0.0d/.')' returned non-zero exit status 2

On RHEL 5.5, I got a similar error building openssl but linker told me that I need to recompile with -fPIC options.

Any help would be appreciated.

Thanks,
-- Amal

**Comment by novoiot** [comment]
Hi Can you please details how you have fixed this, I am trying to cross compile openssl on 32bit powerpc and couldn't successfull
